### ISSUE TITLE
I can't see most screenshot on Github, I have to download them to see them

### ISSUE THREAD

**Issue by Crataegus9** [DataDrivenEcologicalSynthesis/VirtualBiogeography#20]
(broken link or copyright strike I don't know)
-SS_00-01-33_GBR.png
SS_00-01-34_GBR.PNG
SS_00-01-36_GBR.PNG
SS_00-01-37_GBR.png
SS_00-01-48_GBR.PNG
SS_00-02-05_GBR.PNG
.... way too many are deleted,  I don't want to parse through all of them. How should we proceed now? Image inversion won't do the trick, so maybe adding some lateral compression or another modification to the images?

**Comment by indigotran** [comment]
You can't view the image directly on GitHub. The best solution is to clone the repository to your local machine, that way you have access to all the file directly on your computer. The links are not broken, just that sometimes the image file is too large and it won't be displayed on the webpage.

**Comment by Crataegus9** [comment]
Yeah, that’s what I did

**Comment by indigotran** [comment]
@superornitho You already clone the repo and the images still not showing up on your personal computer? Is that right? If this is the case, I can investigate some more and send you all the images in a .zip as well.

**Comment by Crataegus9** [comment]
No, I cloned the repo and it worked that way, sorry if I was misunderstood!

**Comment by Crataegus9** [comment]
@indigotran Everything works on my side!

**Comment by indigotran** [comment]
@superornitho That's great to hear! Please let me know if you ever have any issues with GitHub. I'm here to help.
