### ISSUE TITLE
Re-occurring fish

### ISSUE THREAD

**Issue by EKROFT** [DataDrivenEcologicalSynthesis/VirtualBiogeography#30]
How are we going to account for the same individual re-occurring in multiple shots?

**Comment by phylojenie** [comment]
I think once we count an individual in a given shot, that's will be the only time we could it, especially if it's a named character like Nemo or Dory. However there might be individuals of the same species in different locations in the film, and in that case it would make sense to count them twice, as unique occurrences.

**Comment by aliczner** [comment]
lol I feel like a broken record, but this depends on the research question. I think Jenna answered above perfectly though for the research questions currently on our research question page. None of our questions require keeping track of the same individual at the same location so we don't need to worry about that

**Comment by EKROFT** [comment]
@aliczner yes, most of these issues have already been addressed. The reason we are writing them here is just because it was the homework from last lecture to write them out at issues and solutions, even if we've already dealt with them :)
