### ISSUE TITLE
Addressing aquarium fish assemblages

### ISSUE THREAD

**Issue by indigotran** [DataDrivenEcologicalSynthesis/VirtualBiogeography#31]
Comment on class call: whether we are going to address the realisticness of the fish assemblages in the dentist office's aquarium?

**Comment by phylojenie** [comment]
I believe we discussed saving this for last if we had the time; i.e. given what we know about the species distributions in the wild, does the assemblage in the aquarium make sense?

**Comment by indigotran** [comment]
@phylojenie Yes we already agreed on this, but I just added it as an issue so that we have it on here as a task.

**Comment by aliczner** [comment]
I would say ignore those. We only know where the dentist got Nemo from, but we don't know where he collected, or maybe he was more ethical earlier and bought the other fish from a pet store XD
