### ISSUE TITLE
Large groups

### ISSUE THREAD

**Issue by EKROFT** [DataDrivenEcologicalSynthesis/VirtualBiogeography#32]
How will we deal with very large schools of fish?

**Comment by phylojenie** [comment]
I propose we count large schools of fish like large groups of birds: count a group of 5 or 10, then estimate total number of individuals by visually partitioning groups of 5 or 10 from the large school. We can estimate to the nearest 5, 10 or 100 depending on how large the group is we're looking at.

**Comment by aliczner** [comment]
It may depend on the question we want to ask - are we interested in abundances or just presence/absence?
If just presence absence then it just counts as that species being present so we don't need to count. From my quick look at the datasheet and our research Q page, it doesn't seem like abundances are needed! Much simpler!
