### ISSUE TITLE
Recording sponges, coral and anemones

### ISSUE THREAD

**Issue by phylojenie** [DataDrivenEcologicalSynthesis/VirtualBiogeography#38]
After an initial look at the reef screenshots, I would like to suggest that we don't record occurrence data for sponges, coral, or anemones. There's so many of them in every shot and we don't have any point of reference for which species they might be; they function more as background/structural elements in the movie than part of the ecosystem.

I'm happy for folks to make a case for why we should track this data, but at this point I don't feel like recording 70 occurrences of generic sponge in the reef scenes would add any value to our data.

**Comment by indigotran** [comment]
@phylojenie Maybe not for occurrence frequency, but how about just for identification? Do you still think it's too much work to do?

**Comment by aliczner** [comment]
Could we just record anemone, sponge, coral etc? 
If we want to be a bit more specific could add the colour instead of trying to ID the species. Kind of like a morphospecies description. E.g. Blue coral, red anemone etc.

**Comment by phylojenie** [comment]
Personally, I have zero ID experience with sponges or coral, so I don't feel particularly confident in assigning IDs. We also don't have any of the coral and sponge species on the reference list, so for all we know they could just be made up generic species. If we are really set on including them, I am open to suggestions for how to ID/count these.

@aliczner We could, though I just don't know what value that would add to the project if we don't have species or genus names, since we won't be able to compare them to any real-world data. We would just be tracking "1 blue coral" "2 green anemone" etc.
