### ISSUE TITLE
There are two folders named "data"

### ISSUE THREAD

**Issue by phylojenie** [DataDrivenEcologicalSynthesis/VirtualBiogeography#39]
Two folders are showing up on the online repo name "data". One contains GBIF info and the other contains species list info. However when I pull the repo data onto my local machine everything is combined into one folder. Is anyone else having this issue?

**Comment by indigotran** [comment]
I did the commit that combines the folders but idk why in the online version of the repo, it's not showing the same changes that I made. I'm still investigating this and trying to resolve it.

**Comment by indigotran** [comment]
I resolved the issue by changing the name of the folder to something completely different (from 'Data/data' to 'Databases') so that the problem of case-sensitivity in windows vs GitHub will no longer be a concern. See full resolution and explanation of the issue in #40.
