### ISSUE TITLE
Branch won't update with changes made to master

### ISSUE THREAD

**Issue by phylojenie** [DataDrivenEcologicalSynthesis/VirtualBiogeography#54]
Hey @indigotran maybe you can help me out; I think I've found a reason for past merge conflicts. I've fetched the master origin onto my own computer using the Git desktop app, and when I view the files in the master branch folders I can see the changes you've made to them (like adding your name to the screenshot list). However when I switch over to the branch I'd like to work and make changes in, the changes aren't reflected in those files, even when I update the origin and "rebase" the branch with the master.
So I end up only having the most recent versions of our files on the master branch, and if I make changes to the files in my own branch they are different than the versions everyone else is committing to.

Any idea how I can sort this out?

**Comment by indigotran** [comment]
Can we do a screen share session sometime later today? I want to see what you're looking at specifically. I have TeamViewer and I can have control over the screen. 
Then we can document what we do for the solution on here for the issue.

**Comment by phylojenie** [comment]
@indigotran Ugh never mind, I just figured out how to update it from the master! It wasn't an issue before when we weren't making as many changes but now I have to update from the master every time. 

In GitHub desktop you can Branch >> Update from master and it will pull changes from the master branch into your current branch. Before I was only updating the master and not my own branch.

**Comment by indigotran** [comment]
Yes, that's what you should do every time just to make sure that you have all the latest commits that had been merged into master. 
I thought it was a bigger problem, then an easy solution to that is also to delete what is on your computer, then clone the entire repo back to your local.

**Comment by phylojenie** [comment]
Totally. For whatever reason whenever I tried to see the differences between my branch and the master it was telling me they were identical 🙄 anyways, issue resolved!

**Comment by indigotran** [comment]
Make sure that you pull from master before you compare the branches on your local.
