### ISSUE TITLE
Friday's presentation - Project Wrap-Up

### ISSUE THREAD

**Issue by indigotran** [DataDrivenEcologicalSynthesis/VirtualBiogeography#57]
To track ideas suggestions for what we can present this Friday

**Comment by indigotran** [comment]
1. Present a piece of the data life cycle on how data collection and description is done.
2. Comment on the "fantastical" element depicted in the movie (i.e. how a clownfish travels all the way to Sydney)
3. Create a framework for testing biogeography for other pieces of media
4. Our feelings on the project
5. If we have more time, what would we like to do with this project?

**Comment by EKROFT** [comment]
I added all the "results" maps to the presentation, and also the screenshots you had asked me to take of the data management process. I'm open to them being moved around, it's just to have them there so we have something to work with!

**Comment by phylojenie** [comment]
Hi team,

I added a framework to the presentation that we could use to shape the structure of our presentation using the data life cycle we learned about at the beginning of this course. Let me know what you think about using this structure; it would allow us all to comment on our contributions to the project at each stage of the process and show how our project evolved from start to finish. But if you think this overcomplicates things then no worries.

**Comment by indigotran** [comment]
Hi team @DataDrivenEcologicalSynthesis/virtualbiogeography !

So for the wrap-up presentation this Friday, I proposed this rough structure below. Let me know what you all think and what else we can add/reorganize/etc.

1. Talk about the **data life cycle** and how this integrated into our whole process:
    a. Data collection: data pipeline, collection from the movie + how we set up the collection spreadsheet, interaction with GBIF and API
    b. Data analysis: GIS, teasing out data from the movie,etc.
2. The results graphs from our data and what conclusion we can draw from it
3. Personal feelings and emotional journey through the project

I could see the result being put at the beginning as well since it's what people are here to see, and then we can explain the process of how we get to these conclusions.

**Comment by phylojenie** [comment]
Re: Dr. Poisot's advice about the final slide being our "take home message", I think we can use the report card grading to stand in for that. Our take home message is how we defined accuracy and how we rate each facet of that accuracy, it fits really well!

**Comment by aliczner** [comment]
agreed!

**Comment by indigotran** [comment]
I think we got this! Let's keep working and hopefully be finished by tomorrow evening. Is 5 PM ET a good time for everyone to meet tomorrow for a practice run of the presentation? @superornitho @phylojenie @aliczner @EKROFT

**Comment by EKROFT** [comment]
5pm works for me

**Comment by aliczner** [comment]
Unsure yet how tomorrow will be- part of what made yesterday rough, on top of getting kicked out of the apartment for the day, was a close family member on my spouse's side passed away suddenly yesterday. It very likely will be fine, but if I can't make it I'll try and at least time my parts so we can figure out length of presentation and stuff!

**Comment by indigotran** [comment]
@aliczner I'm so sorry to hear that. Please take the time you need to care for yourself first, the rest of us will figure out how to best accommodate your part of the presentation. Let me know anything I can help with.

**Comment by phylojenie** [comment]
@aliczner Take care of yourself, we will be able to organize the presentation if you're not able to.

@team: I have also lost my workspace for the day and I need to continue unpacking, but tomorrow first thing I will continue organizing and arranging the presentation. If this isn't soon enough I will try to find some time later this evening.

**Comment by indigotran** [comment]
I just added the diagram for the data life cycle. Let me know what you think and what needed to be tweaked.

**Comment by aliczner** [comment]
I finished up the GBIF slides, let me know if you would like any changes
